### ISSUE TITLE
how to make datasets

### ISSUE THREAD

**Issue by birdflies** [jonepatr/genea_visualizer#14]
Dear Hi, @jonepatr , Do you know how to make bvh datasets as same as the format of GENEA Challenge 2020?

**Comment by ghenter** [comment]
Following [this discussion on exactly the same topic in another repository](https://github.com/Svito-zar/gesticulator/discussions/37), I believe this issue can be closed.

**Comment by Svito-zar** [comment]
I agree with @ghenter  and hence close the issue now
