### ISSUE TITLE
Security vulnerabilty

### ISSUE THREAD

**Issue by haby0** [jonepatr/genea_visualizer#16]
What would be the right contact to report a security vulnerabilty? thanks!

**Comment by Svito-zar** [comment]
@haby0, thank you for the question. Please email Patrik Jonell at pjjonelll@kth.se

**Comment by haby0** [comment]
> pjjonelll@kth.se

The vulnerability information has been sent to your mailbox.

**Comment by haby0** [comment]
@Svito-zar Google email reminder: Because the system cannot find the email address pjjonelll@kth.se, or the address cannot receive emails, your email cannot be delivered.

**Comment by Svito-zar** [comment]
Oh, sorry, I made a typo there. It should be pjjonell@kth.se

**Comment by haby0** [comment]
> Oh, sorry, I made a typo there. It should be [pjjonell@kth.se](mailto:pjjonell@kth.se)

Please accept.
