### ISSUE TITLE
Couldn't connect to Docker daemon at http+docker://localhost

### ISSUE THREAD

**Issue by jinhonglu** [jonepatr/genea_visualizer#3]
Hi, I just installed a fresh copy from Ubuntu 20.04.1.

I followed the instruction to install docker-compose. Then I get this error when I 'docker-compose up --build'

Are there any additional packages that I have to install?

**Comment by Svito-zar** [comment]
@jinhonglu , could you please add your error log to this issue?

**Comment by jinhonglu** [comment]
jinhong@jinhong-VirtualBox:~/Desktop/genea_visualizer$ docker-compose up --build
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by jonepatr** [comment]
This seems like docker is not running on your system.
Please try: `sudo systemctl enable docker` or google for instructions on how to run docker on your system.

**Comment by jinhonglu** [comment]
jinhong@jinhong-VirtualBox:~/Desktop/genea_visualizer$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-12-14 13:45:36 GMT; 2min 54s ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 15640 (dockerd)
      Tasks: 10
     Memory: 113.5M
     CGroup: /system.slice/docker.service
             └─15640 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Dec 14 13:45:35 jinhong-VirtualBox dockerd[15640]: time="2020-12-14T13:45:35.404600532Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Dec 14 13:45:35 jinhong-VirtualBox dockerd[15640]: time="2020-12-14T13:45:35.404704253Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Dec 14 13:45:35 jinhong-VirtualBox dockerd[15640]: time="2020-12-14T13:45:35.405039310Z" level=info msg="Loading containers: start."
Dec 14 13:45:35 jinhong-VirtualBox dockerd[15640]: time="2020-12-14T13:45:35.577656809Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0>
Dec 14 13:45:35 jinhong-VirtualBox dockerd[15640]: time="2020-12-14T13:45:35.807737326Z" level=info msg="Loading containers: done."
Dec 14 13:45:35 jinhong-VirtualBox dockerd[15640]: time="2020-12-14T13:45:35.946754964Z" level=info msg="Docker daemon" commit=afacb8b7f0 graphdriver(s)=overlay2 version>
Dec 14 13:45:35 jinhong-VirtualBox dockerd[15640]: time="2020-12-14T13:45:35.947905057Z" level=info msg="Daemon has completed initialization"
Dec 14 13:45:36 jinhong-VirtualBox systemd[1]: Started Docker Application Container Engine.
Dec 14 13:45:36 jinhong-VirtualBox dockerd[15640]: time="2020-12-14T13:45:36.006504237Z" level=info msg="API listen on /run/docker.sock"
Dec 14 13:45:39 jinhong-VirtualBox dockerd[15640]: time="2020-12-14T13:45:39.766449176Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks>


I checked the docker status, it shows it is running, but i still get the same error.

**Comment by guofengming11** [comment]
> jinhong@jinhong-VirtualBox:~/Desktop/genea_visualizer$ docker-compose up --build
> ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
> 
> If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

i get the same error, how did you solve it , thanks

**Comment by jinhonglu** [comment]
> > jinhong@jinhong-VirtualBox:~/Desktop/genea_visualizer$ docker-compose up --build
> > ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
> > If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
> 
> i get the same error, how did you solve it , thanks

Sorry for the late reply, I solved it with running the command with sudo
