### ISSUE TITLE
problem on server building

### ISSUE THREAD

**Issue by kelvinqin** [jonepatr/genea_visualizer#4]
Hi Dear Patrik,  thanks for your work.  I am using a Ubuntu 16.04, when I run the following command I met a problem. 

**sudo /usr/local/bin/docker-compose up --build**

WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker
Pulling redis (redis:latest)...
ERROR: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

Look forward to your help,

FYI about my docker-compose:
**sudo /usr/local/bin/docker-compose --version**
WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker
docker-compose version 1.18.0, build 8dd22a9

Kelvin

**Comment by jonepatr** [comment]
Hi Unsure what has gone wrong here, but seems like there is something wrong with your docker-compose/docker setup. 
A quick google came up with these suggestions: 
* https://github.com/docker/compose/issues/4569
* https://gist.github.com/jonatanblue/e6c319aa95673eaf8acc475f92e961d5

Please try out what they suggest there and let me know if it helped or not!

**Comment by kelvinqin** [comment]
Patrik,
Thanks, I will update you,
Kelvin

Patrik Jonell <notifications@github.com> 于2020年12月28日周一 下午5:51写道：

**Comment by kelvinqin** [comment]
Dear Patrik,
Today when I try again the command "sudo /usr/local/bin/docker-compose up --build", very strange, it went through amazingly. (I did not do any thing)

The only regret thing is that I should not using sudo, which cause I got some warning like "/usr/local/lib/python3.6/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
 absolutely not recommended!

Anyway, I have generated a nice video using my bvh (which I generated with Taras and Simon's great help)

I still have one more question ---
What I send to server is a bvh file which contain fullbody motion, but the output is a video only about upper body, is it possible for me to generate a full body video pls?

Attached please see my BVH and MP4 (I merged the corresponding audio in offline way)

input bvh: [temp.zip](https://github.com/jonepatr/genea_visualizer/files/5757624/temp.zip)
output video: [temp_av.zip](https://github.com/jonepatr/genea_visualizer/files/5757623/temp_av.zip)

May you, Taras and Simon a wonderful 2021,
Kelvin

**Comment by jonepatr** [comment]
Good to hear that it's working!

Regarding your second  question, we use a 3d model (https://github.com/jonepatr/genea_visualizer/blob/master/celery-queue/gesturer_mesh.fbx) which only has the upper body. You can use  your own model instead, however, you would also need to adjust the model specific tweaks in https://github.com/jonepatr/genea_visualizer/blob/master/celery-queue/blender_render.py as well.

**Comment by kelvinqin** [comment]
Patrik,
Thanks so much, I am reading blender_render.py now. The logic seems that it was running inside Blender environment using python API, the working flow is:
1> create a scene
2>  set camera, light, 
3>  load animation from fbx file (in our case, it is gesture_mesh.fbx, does it  only contain the static gesture information? or it contains motion data also like bvh?)
4> then load animation from bvh (in our case, it is my bvh file)
5> previously when I generated BVH file, I indeed noticed that there is a joint inside my bvh named pCube0, I don't understand what it is for? 
6> from line 74, " (bvh_obj,) = set(context.scene.objects) - old_objs", I fully got lost, :-)....

Before going deep, I think that may lack a lot of basic knowledge on fbx and bvh. To my current knowledge, FBX and BVH can be converted to each other.  But maybe I am wrong.

Can you share some level of knowledge on what is FBX and what is BVH, what is the relationship between them? I searched some relevant information from INTERNET in the past, from which I got an idea, both of them are a model to describe skeleton animation?

Thanks! And sorry for so many questions, silly questions :-)
Have a nice day,

**Comment by kelvinqin** [comment]
Patrik,
I noticed that this work by Simon, https://youtu.be/egf3tjbWBQE?t=168, not sure if that is the same model but with a full body? Do you have a plan to support a full body 3D model in future?

Thanks,
Kelvin

**Comment by ghenter** [comment]
As explained in the readme, this visualiser was developed specifically for the GENEA Challenge 2020. That challenge evaluated only upper body motion. The 2020 challenge is now over and the visualiser is public so that people can replicate the challenge results and compare their work against the methods from there.

For the time being, there are no plans to extend the visualiser beyond the scope of the challenge. If someone implements full body 3D motion, they can do a pull request.
