### ISSUE TITLE
Failed with bvh file obtained from OpenPose joint

### ISSUE THREAD

**Issue by teshima058** [jonepatr/genea_visualizer#6]
I used [video2bvh](https://github.com/KevinLTT/video2bvh) to get a bvh file from a video. In video2bvh, it seems that the 2D-joints are estimated by OpenPose and it is lifted to 3D-joints by 3d-pose-baseline. [Here](https://drive.google.com/file/d/1F5_TUN_KyLibIUFMpkjEhPGGcE3P6sGG/view?usp=sharing) is a sample bvh file I output.

However, the visualizer doesn't seem to work in this format.
How can I convert the 3D coordinates of the 8 upper body joints obtained by OpenPose into a bvh file that can be handled by this visualizer?

**Comment by Svito-zar** [comment]
Dear @teshima058 ,

The script in this repo can only visualize BVH files for the motions of a specific skeleton from the GENEA dataset.

For using a different skeleton you would need to do several things:
1. Replace [gender_mesh.fbx](https://github.com/jonepatr/genea_visualizer/blob/master/celery-queue/gesturer_mesh.fbx) with the skeleton corresponding to your data
2. Remove the [postprocessing code](https://github.com/jonepatr/genea_visualizer/blob/1d0ca413806ebd68e55f9c6bc2c62c2781b85abf/celery-queue/blender_render.py#L50-L68)

Hope it helps,
Taras

**Comment by teshima058** [comment]
Dear @Svito-zar 
Thank you so much for your answer.
I would like to apply this visualizer to OpenPose joints by myself.

**Comment by birdflies** [comment]
> Dear @Svito-zar
> Thank you so much for your answer.
> I would like to apply this visualizer to OpenPose joints by myself.

@teshima058  Dear，do you solve this problem？I have a similar problem
