### ISSUE TITLE
Get "list index out of range" error

### ISSUE THREAD

**Issue by zhiqizhang** [jonepatr/genea_visualizer#8]
Thank you very much for sharing this visualization tool. I want to set up this tool to text our results. 
I built the docker according to the README. When I ran the example.py with the bvh file you provided in "GENEA Challenge 2020 submitted BVH files", I got the "list index out of range" error. I wonder what is the reason? 
Thanks

**Comment by Svito-zar** [comment]
Dear @zhiqizhang ,
Could you please provide the full error trace?
Also, details about your OS and python environment would be helpful.
Best,
Taras

**Comment by zhiqizhang** [comment]
thank you very much for the information. 

 python example.py newbvh.bvh 
Processing the file (this can take a while depending on file size)
Traceback (most recent call last):
  File "example.py", line 63, in <module>
    raise Exception(response["result"])
Exception: list index out of range

I am on ubuntu;  python 3.8.8
And I am build your docker-composer build the container. 
cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.2
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

**Comment by zhiqizhang** [comment]
we finally fixed the problem. It is because of the http_proxy which makes the bvh file can't be transferred between different containers. 
Just want to update and incase someone have the same issues as us. Thanks
